---
title: "Assignment 3"
author: "Delaney Parke"
date: "2026-03-19"
output: pdf_document
---

```{r}
#loading library
library(tidyverse)
library(dplyr)
library(stringr)
library(lubridate)
library(plotly)
library(readxl)
library(readr)
library(scales)
library(qicharts2)
```

```{r}
#reading in dataset
mass <- read.csv("ncesdata.csv")
head(mass)
```
```{r}
mass <- mass |>
  mutate(across(c('Students', 'Teachers','Directly.Certified', 'Student.Teacher.Ratio', ), as.numeric))
```

```{r}
dim(mass)
```

```{r}
names(mass)
```

```{r}
str(mass, width = 70, strict.width = 'cut')
```

```{r}
table(unlist(sapply(mass, class)))
```

```{r}
# absolute values
absoluteT <- table(mass$Locale,
                 useNA = "ifany") #include all values!
#here you are:
absoluteT
```


```{r}
table <-prop.table(absoluteT)
table
```

```{r}
propT <-prop.table(absoluteT)*100

propT
```

```{r}
(tableFreq=as.data.frame(absoluteT))
```

```{r}
names(tableFreq)=c("Locale","Count")
# adding percents:
tableFreq$Percent=as.vector(propT)
# then, you have:
tableFreq
```

```{r}
base= ggplot(data = tableFreq, 
             aes(x = reorder(Locale, Percent), # horizontal
                 y = Percent)) #vertical

plot1 <- base + 
  geom_col() +
  geom_text(aes(label = paste0(round(Percent, 1), "%")), vjust= -0.3) + theme(axis.text.x = element_text(angle = 50, hjust =1)) +
  ylim(0, max(tableFreq$Percent) * 1.1)

# geom_bar(stat = 'identity') # alternative
plot1
```

```{r}
titleText='Where are the greatest number of schools located?'
sub_titleText='Massachusetts 2024-2025'
sourceText='Source: US Department of Education'
# are these obvious?
x.AxisText="Locations"
y.AxisText="Count"

plot2 = plot1 + labs(title=titleText,
                     subtitle = sub_titleText,
                     x =NULL,  #x.AxisText
                     y = NULL, #y.AxisText
                     caption = sourceText) 
plot2
```

```{r}
length(unique(mass$Student.Teacher.Ratio))
```

```{r}
summary(mass$Student.Teacher.Ratio)
```

```{r}
mass_percent <- mass |>
  mutate(Student.Teacher.Ratio.Cat = cut(Student.Teacher.Ratio, 
                                         breaks = seq(0, 50, by = 5))) |>
  group_by(Student.Teacher.Ratio.Cat) |>
  summarize(Percent = n() / nrow(mass) * 100)

mass_percent
```

```{r}
mass_percent_pareto <- mass_percent |>
  filter(!is.na(Student.Teacher.Ratio.Cat)) |>
  arrange(desc(Percent)) |>
  mutate(CumPercent = cumsum(Percent))
```

```{r}
parplot <- ggplot(mass_percent_pareto, aes(x = reorder(Student.Teacher.Ratio.Cat, -Percent), y = Percent)) +
  geom_col(fill = "grey", color = "black") +                      # bars
  geom_line(aes(y = CumPercent), group = 1, color = "red", size = 1) +  # cumulative line
  geom_point(aes(y = CumPercent), color = "red", size = 2) +             # cumulative points
  scale_y_continuous(
    name = "Percent of Schools",
    labels = percent_format(scale = 1),
    sec.axis = sec_axis(~ ., name = "Cumulative Percent")  # secondary axis for cumulative
  ) +
  labs(
    x = "Student-Teacher Ratio Bin",
    title = "Pareto Chart of Student-Teacher Ratios",
    subtitleText="Massachusetts 2024-2025",
    caption= "Source: US Department of Education"
  ) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

parplot
```

